services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:9.3
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
      - symfony
###< doctrine/doctrine-bundle ###
  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: database
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DEFAULT_DB_NAME: ${MYSQL_DATABASE:-app}
      ADMINER_DESIGN: lucas-sandery
    ports:
      - "8080:8080"
    networks:
      - symfony # Docker containers (services) that need to connect to each other should be on the same network.
  php-nginx:
    build:
      context: ./.docker
      dockerfile: Dockerfile-php-nginx
    volumes:
      - ./:/var/www/project/
    ports:
      - 8000:80 # Ports that are exposed, you can connect to port 8001 to port 80 of the container.
    networks:
      - symfony
  php-fpm:
    build: # Info to build the Docker image
      context: ./.docker # Specify where the Dockerfile is located (e.g. in the root directory of the project)
      dockerfile: Dockerfile-php # Specify the name of the Dockerfile
    environment: # You can use this section to set environment variables. But you can also use the .env file.
      - DATABASE_URL=mysql://root:password@database:3306/app?serverVersion=9.3&charset=utf8mb4
    volumes:
      - ./:/var/www/project/ # Location of the project for php-fpm. Note this should be the same for NGINX.*
    networks:
      - symfony # Docker containers (services) that need to connect to each other should be on the same network.

networks:
  symfony:

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
